name: Deploy mkdocs

on:
  workflow_call:
    secrets:
      semantic-release-token:
        description: 'GitHub token for semantic release'
        required: true
      npm-token:
        description: 'NPM token for semantic release'
        required: true

env:
  HUSKY: 0
  GITHUB_TOKEN: ${{ secrets.semantic-release-token }}
  NPM_TOKEN: ${{ secrets.npm-token }}

jobs:
  release:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        env:
          GITHUB_TOKEN: ${{ secrets.mkdocs-token }}
          CONFIG_FILE: mkdocs.yml
          # GITHUB_DOMAIN: github.myenterprise.com
          REQUIREMENTS: requirements.txt
